main:
  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490
  # Screen Geometry
  #screenWidth: 1024
  #screenHeight: 768
  screenWidth: 800
  screenHeight: 480

  # Set EFIS to occupy the entire screen without system border / menu
  screenFullSize: True

  # Screen background color RGB
  screenColor: (0,0,0)

  # If left out the first defined screen will be default
  defaultScreen: EMS

menu:
  menus:
  # The button configuration is ['button text', 'action', 'argument']
  # Currently limited to 6 buttons.  Comment out this entire section to hide menus if you are using real buttons.
      PFDMenu:
          - ['Hide', 'activate menu', 'ShowMenu']
          - ['Back', 'Show Previous Screen','']
          - ['Next', 'Show Next Screen','']
          - ['EMS', 'Show Screen','EMS']
          - ['Units', 'Set Instrument Units', 'OAT,OILT1,Temperature:Toggle']
          - ['Basic', 'activate menu','BasicMenu']
      BasicMenu:
          - ['Hide', 'activate menu', 'ShowMenu2']
          - ['PFD', 'Show Screen','PFD']
          - ['EPFD', 'Show Screen','EPFD']
          - ['EMS', 'Show Screen','EMS']
          - ['Six', 'Show Screen','SixPack']
          - ['Config', 'activate menu','ConfigMenu']
      ConfigMenu:
          - ['Hide', 'activate menu', 'ShowMenu3']
          - ['Back', 'Show Previous Screen','']
          - ['Next', 'Show Next Screen','']
          - ['Baro -', 'Change Value','BARO,-0.01']
          - ['Baro +', 'Change Value','BARO,0.01']
          - ['Leaning', 'activate menu','EMSMenu']
      EMSMenu:
          - ['Hide', 'activate menu', 'ShowMenu4']
          - ['Norm', 'Set EGT Mode','Normalize']
          - ['Peak', 'Set EGT Mode','Peak']
          - ['Lean', 'Set EGT Mode','Lean']
          - ['Rst Pk', 'Set EGT Mode','Reset Peak']
          - ['PWR', 'activate menu','PWRMenu']
      
      PWRMenu:
          - ['Back', 'activate menu', 'EMSMenu']
          - ['Back', 'activate menu', 'EMSMenu']
          - ['Back', 'activate menu', 'EMSMenu']
          - ['Back', 'activate menu', 'EMSMenu']
          - ['Back', 'activate menu', 'EMSMenu']
          - ['PWR OFF', 'sys com','sudo shutdown now']
          
      ShowMenu:
          - ['Show', 'activate menu','PFDMenu']
      ShowMenu2:
          - ['Show', 'activate menu','BasicMenu']
      ShowMenu3: 
          - ['Show', 'activate menu','ConfigMenu']
      ShowMenu4: 
          - ['Show', 'activate menu','EMSMenu']

  start_menu: ShowMenu4
#  show_time: 3  # hides the menu after 3 seconds.  However cannot show again.  Don't use.  Here for reference only.
  number_of_buttons: 6
  buttons_spacing: 130
  left_margin: 20
  top_margin: 440

# The keybindings are used to attach keystrokes to actions.  The key can be
# a string that represents a key Sequence.  See the documentation for more
# information about key sequences and actions.
keybindings:
  - key: A
    action: Show Previous Screen

  - key: S
    action: Show Next Screen

  - key: P
    action: Show Screen
    args: PFD

  - key: M
    action: Set Airspeed Mode

#  - key: Q
#    action: Set Value
#    args: BTN6, True
#    direction: DN
#  - key: Q
#    action: Set Value
#    args: BTN6, False
#    direction: UP
  - key: U
    action: Set Instrument Units
    args: OAT,OILT1,EGTMAX1,Temperature:Toggle

  - key: F1
    action: Activate Menu Item
    args: 1
  - key: F2
    action: Activate Menu Item
    args: 2
  - key: F3
    action: Activate Menu Item
    args: 3
  - key: F4
    action: Activate Menu Item
    args: 4
  - key: F5
    action: Activate Menu Item
    args: 5
  - key: F6
    action: Activate Menu Item
    args: 6

  - key: ']'
    action: Change Value
    args: BARO,0.01
  - key: '['
    action: Change Value
    args: BARO,-0.01

# Data bindings tie actions to values in teh database
# key is the database key and should match the FIX Gateway key
databindings:
  - key: BTN1
    condition: True
    action: Activate Menu Item
    args: 1
  - key: BTN2
    condition: True
    action: Activate Menu Item
    args: 2
  - key: BTN3
    condition: True
    action: Activate Menu Item
    args: 3
  - key: BTN4
    condition: True
    action: Activate Menu Item
    args: 4
  - key: BTN5
    condition: True
    action: Activate Menu Item
    args: 5
  - key: BTN6
    condition: True
    action: Activate Menu Item
    args: 6
#  - key: ENC1
#    action: Menu Encoder
#    args: <VALUE>   # This sends the data value to the action
#  - key: OILP1
 #   condition: < 25
  #  action: Show Screen
   # args: EMS


# This section defines FIX IDs that we'll write out to the
# FIX Gateway server.  Each can be defined as one of three
# methods.  Interval will look at the time out lifetime (TOL)
# of the point and send the data at half that interval.
# OnChange will send when the value is changed and Both will
# do both.
outputs:
 # TAS = Interval
  BARO: Interval
  BTN16: OnChange


# Screen definitions describe the screens that will be loaded
# and ready for use.  Each section should start with "Screen."
# followed by the name.  The only required configuration is
# module, which is the module that will be loaded to render
# the screen

screens:
#  EPFD:
#    module: pyefis.screens.epfd
#    title: Primary Flight Display
#    dbpath: /home/debian/.makerplane/data/CIFP/FAACIFP18
#    indexpath: /home/debian/.makerplane/data/CIFP/index.bin
#    check_engine: [MAP1, TACH1, OILP1, OILT1, FUELQT, FUELF1, CHTMAX1, EGTAVG1]
#    update_period: .1

#  PFD:
#    module: pyefis.screens.pfd
#    title: Primary Flight Display
#    dbpath: /home/debian/.makerplane/data/CIFP/FAACIFP18
#    indexpath: /home/debian/.makerplane/data/CIFP/index.bin
#    update_period: .1

  EMS:
    module: pyefis.screens.ems_sm
    title: Engine Management

#  SixPack:
#    module: pyefis.screens.sixpack
#    title: Standard Instrument Panel

#  PFDSM:
#    module: pyefis.screens.pfd_sm
#    title: PFD Small

  #Test:
  #  module: pyefis.screens.test
  #  title: Test Screen

# Hooks are user defined modules that are loaded at specific points
# in the programs execution.  Right now their is only one place and
# it is right after all of the initialization and just before the
# main window and default screen are shown.  We'll add more as the
# need arises.
hooks:
  # Keys:
  #   module: user.hooks.keys
  # Composite:
  #   module: user.hooks.composite


# Logging configuration - See Python logging.config module documenation
# Logging configuration - See Python logging.config module documenation
logging:
  version: 1
  disable_existing_loggers: False
  loggers:
    '':
      # messages with levels below the one given will not be logged
      #level: DEBUG
      level: INFO
      #level: WARNING
      #level: ERROR
      #level: CRITICAL

      handlers: [stderr, file]
      propagate: True

  formatters:
    standard:
      format: "%(levelname)s:%(asctime)s:%(name)s - %(message)s"
      datefmt: "%Y%m%d-%H:%M:%S"
      class: logging.Formatter

  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stderr

    file:
      class: logging.FileHandler
      formatter: standard
      filename: fixgw.log
      mode: w
      #mode: a

    syslog:
      class: logging.handlers.SysLogHandler
      formatter: standard
